
/* 1. Валюты - DEF RUR */
create table CURRENCY (
ID INT NOT NULL PRIMARY KEY,
NAME varchar(10) NOT NULL UNIQUE,
EXT varchar(3) NOT NULL UNIQUE
);

/* 2.  Счета */
create table ACCOUNT (
ID INT NOT NULL PRIMARY KEY,
NAME varchar(100) NOT NULL,
DESCRIPTION varchar(1024),
CURRENCY INT NOT NULL REFERENCES CURRENCY(ID),
TYPE INT NOT NULL DEFAULT 0, /* 0-текущие счета, 1-Кредиты, 2-Депозиты */
CLOSED DATE,
CHECK (TYPE in (0, 1, 2))
);

/* 3. */
create table CATEGORY (
ID INT NOT NULL PRIMARY KEY,
NAME varchar(100) NOT NULL,
PARENT INT,
TYPE INT NOT NULL DEFAULT 0, /*тип 0-расход 1-приход 2-перевод*/
CHECK (TYPE in (0, 1, 2)) );

/* 5. Проекты */
create table PROJECT (
ID INT NOT NULL CONSTRAINT PROJECT_PK PRIMARY KEY,
NAME varchar(100) NOT NULL,
PARENT INT /*REFERENCES PROJECT(ID)*/,
DESCRIPTION varchar(1024),
CREATED DATE NOT NULL DEFAULT CURRENT_DATE,
CLOSED DATE,
STATE INT NOT NULL DEFAULT 0, /*тип 0-только создан, 1-открыт 2-исполнен 3-отменен */
CHECK (STATE in (0, 1, 2, 3))
);

/* 6. платежи */
create table PAY (
ID INT NOT NULL PRIMARY KEY,
NAME varchar(100),
ACCOUNT INT NOT NULL REFERENCES ACCOUNT(ID),
CREATED DATE NOT NULL DEFAULT CURRENT_DATE,
AMOUNT NUMERIC(12, 2) NOT NULL, /*минус - расход + - приход*/
CATEGORY INT REFERENCES CATEGORY(ID), /* категория платежа */
ACCOUNT_TO INT REFERENCES ACCOUNT(ID), /* в случае перевода на др. счет */
DESCRIPTION varchar(1024),
PROJECT INT REFERENCES PROJECT(ID),
NUMBER_OF INT, /* кол-во*/
NUMBER_OF2 INT
);

/* 7. Планы */
create table PLAN (
ID INT NOT NULL PRIMARY KEY,
NAME varchar(100),
STARTED DATE NOT NULL,
ENDED DATE NOT NULL,
CATEGORY INT REFERENCES CATEGORY(ID), /*кто-то 1 категория или проект */
PROJECT INT REFERENCES PROJECT(ID),
AMOUNT NUMERIC(12, 2) NOT NULL,
NUMBER_OF INT
)