INSERT INTO CURRENCY (ID, NAME, EXT) VALUES (0, 'RUR', 'Р');
INSERT INTO CURRENCY (ID, NAME, EXT) VALUES (1, 'USD', '$');
INSERT INTO CURRENCY (ID, NAME, EXT) VALUES (2, 'EUR', 'E');

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (1, 'Супермаркет', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (10, 'Продукты', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (11, 'Бытовая химия', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (12, 'Домашним питомцам', 1, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (2, 'Дом', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (20, 'Коммуналка', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (21, 'Инструменты', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (22, 'Квартира ремонт, материалы', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (23, 'Ипотека', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (24, 'Участок ремонт, материалы', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (25, 'Огородничество', 2, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (3, 'Машина', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (30, 'Бензин', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (31, 'Расходники', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (32, 'Штрафы', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (33, 'Ремонт', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (34, 'Стоянка', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (35, 'Инструмент', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (36, 'Бумажные расходы', 3, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (4, 'Семья', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (40, 'Завтраки-обеды', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (41, 'Телефоны-интернеты', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (42, 'Спорт-секции', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (43, 'Школа-обучение', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (44, 'Лечение', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (45, 'Работа за деньги', 4, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (5, 'Я', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (50, 'Услуги', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (51, 'Алкоголь', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (52, 'Обеды', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (53, 'Рабочие расходы', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (54, 'Развлекухи', 5, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (6, 'Вещи-гаджеты', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (60, 'Гаджеты', 6, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (61, 'Одежда-обувь', 6, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (62, 'Всякая фигня', 6, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (7, 'Отдых-развлечения', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (70, 'Инвентарь для акт. Отдыха', 7, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (71, 'Походы-путешествия', 7, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (72, 'Развлекательные мероприятия', 7, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (8, 'Всё остальное', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (80, 'Подарки друзьям-родств', 8, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (81, 'Помощь друзьям-родств', 8, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (82, 'Нака', 8, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (83, 'Хз-куда', 8, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (9, 'Зарплата', NULL, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (90, 'Банк', 9, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (91, 'Вуокса', 9, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (92, 'Нестабильные', NULL, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (93, 'Заработки', 92, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (94, 'Подарки', 92, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (95, '%% по вкладу-карте', 92, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (96, 'Cashback по карте', 92, 1);

INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (1, 'CASH', 0, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (4, 'Заначка', 0, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (5, 'Зарплатная Visa PTKB', 0, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (6, 'VISA SBER', 0, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (7, 'Вклад - на ипотеку', 0, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (8, 'Зарплатный счет в ПТКБ', 0, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (11, '$USD До востребования', 1, 0);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (2, 'Депозит RUR', 0, 2);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (9, 'Долги отданные', 0, 2);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (3, 'Должен', 0, 1);
INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (10, 'Я Взял в Долг', 0, 1);

INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (1, 'Я', null, 'Это я');
INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (2, 'Семья', null, 'Группа - Семья');
INSERT INTO PERSON (ID, NAME, PARENT) VALUES (20, 'Оля', 2);
INSERT INTO PERSON (ID, NAME, PARENT) VALUES (21, 'Анита', 2);
INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (3, 'Друзья', null, 'Группа - Друзья');
INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (4, 'Продавцы', null, 'Группа - Продавцы');

INSERT INTO PROJECT (ID, NAME, PARENT, DESCRIPTION) VALUES (1, 'Дом', null, 'Все проекты внутри самого дома');
INSERT INTO PROJECT (ID, NAME, PARENT, DESCRIPTION) VALUES (10, 'Олина комната', 1, 'Дом:Мебель-ремонт-оборудование:Оле комната');
INSERT INTO PROJECT (ID, NAME, PARENT, DESCRIPTION) VALUES (11, 'Полы в доме', 1, 'Дом:Ремонт:Полы в доме');

INSERT INTO PROJECT (ID, NAME, PARENT, DESCRIPTION) VALUES (2, 'Усадьба', null, 'Все проекты на участке вокруг дома');
INSERT INTO PROJECT (ID, NAME, PARENT, DESCRIPTION) VALUES (20, 'Баня', 2, 'Дом:Баня');
INSERT INTO PROJECT (ID, NAME, PARENT, DESCRIPTION) VALUES (21, 'Забор с соседями', 2, 'Дом:Забор с соседями где баня')