INSERT INTO CURRENCY (ID, NAME, EXT) VALUES (0, 'RUR', 'Р');
INSERT INTO CURRENCY (ID, NAME, EXT) VALUES (1, 'USD', '$');
INSERT INTO CURRENCY (ID, NAME, EXT) VALUES (2, 'EUR', 'E');

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (1, 'Продукты', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (11, 'Молочка-яйца', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (12, 'Сладости', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (13, 'Фрукты-овощи', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (14, 'Крупы-хлеб', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (15, 'Мясо', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (16, 'Рыба-морепродукты', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (17, 'Напитки', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (18, 'Прочее-разное', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (19, 'Хозяйственные', 1, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (20, 'Зверям-питомцам', 1, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (2, 'Машина', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (21, 'Бензин', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (22, 'Масла-фильтра', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (23, 'Расходники', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (24, 'Шины', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (25, 'Штрафы', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (26, 'Бумажные расходы', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (27, 'Стоянка', 2, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (28, 'Ремонт', 2, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (3, 'Семья', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (30, 'Завтраки-обеды', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (31, 'Мероприятия-поездки', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (32, 'Связь-телефоны', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (33, 'Гаджеты-вещи', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (34, 'Одежда', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (35, 'Школа', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (36, 'Образование-спорт', 3, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (37, 'Лечение', 3, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (4, 'Дом', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (40, 'Коммуналка', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (41, 'Материалы-ремонт', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (42, 'Инструменты', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (43, 'Предметы обихода', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (44, 'Ипотека-долг', 4, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (45, 'Ипотека-проценты', 4, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (5, 'Личные(Я)', NULL, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (50, 'Обед', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (51, 'Развлекухи', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (52, 'Алкоголь', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (53, 'Услуги', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (54, 'Хобби', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (55, 'Работа', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (56, 'Лечение', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (57, 'Одежда', 5, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (58, 'Гаджеты-вещи', 5, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (6, 'Всё остальное', NULL, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (60, 'Родственники', 6, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (61, 'Друзья', 6, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (62, 'Разное', 6, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (63, 'Нака', 6, 0);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (64, 'Переоценка', 6, 0);

INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (7, 'Банк-зарплата', NULL, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (8, 'Вуокса-зарплата', NULL, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (9, 'Заработки', NULL, 1);
INSERT INTO CATEGORY (ID, NAME, PARENT, TYPE) VALUES (10, 'Подарки', NULL, 1);

INSERT INTO ACCOUNT (ID, NAME, CURRENCY, TYPE) VALUES (10, 'CASH', 0, 0);

INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (1, 'Я', null, 'Это я');
INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (2, 'Семья', null, 'Группа - Семья');
INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (3, 'Друзья', null, 'Группа - Друзья');
INSERT INTO PERSON (ID, NAME, PARENT, DESCRIPTION) VALUES (4, 'Продавцы', null, 'Группа - Продавцы');
INSERT INTO PERSON (ID, NAME, PARENT) VALUES (5, 'Оля', 2)